#!/bin/bash

AccessTokenUri="https://japaneast.api.cognitive.microsoft.com/sts/v1.0/issuetoken"
ttsServiceUri="https://japaneast.tts.speech.microsoft.com/cognitiveservices/v1"
apiKey=$ttsapikey

uname=$(uname)
if [ $uname == 'Darwin' ]; then
	mktemp_com="mktemp"
	play_com="afplay"
elif [ "$(expr substr $uname 1 5)" == 'Linux' ]; then
	mktemp_com="mktemp"
	play_com="paplay"
fi

# See https://docs.microsoft.com/ja-jp/azure/cognitive-services/speech-service/language-support#text-to-speech
ttsLang="ja-JP"
ttsGender="Female"
ttsName="ja-JP-NanamiNeural"

comName=$(basename $0)

if [ "$1" == "" ]; then
	echo "${comName} 'Japanese sentence to be pronounced'"
	exit
fi

text=$1

if [ ${#text} -ge 1000 ]; then
	echo "Azure TTS can handle the text up to 1,000 bytes."
	exit
fi

access_token=$(curl -sS -w '\n' ${AccessTokenUri} -XPOST --data "" -H "Ocp-Apim-Subscription-Key: ${apiKey}" -H "Content-Length: 0")

if [ "${access_token}" != "" ]; then
	data="<?xml version=\"1.0\"?><speak version=\"1.0\" xmlns=\"http://www.w3.org/2001/10/synthesis\" xmlns:mstts=\"https://www.w3.org/2001/mstts\" xml:lang=\"${ttsLang}\"><voice name=\"${ttsName}\">${text}</voice></speak>"
	tmpFile=$(${mktemp_com})
	echo $tmpFile
	result=$(curl -o ${tmpFile} -sS -w '\n' ${ttsServiceUri} -XPOST --data "${data}" \
		-H "Content-type: application/ssml+xml" \
		-H "X-Microsoft-OutputFormat: riff-24khz-16bit-mono-pcm" \
		-H "Authorization: Bearer ${access_token}")
	${play_com} $tmpFile
fi
